//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.Models
{
    using System;
    
    public partial class getProductWithAttribute_Result1
    {
        public int id { get; set; }
        public string name { get; set; }
        public string attribute_name { get; set; }
        public string attribute_value { get; set; }
    }
}
