//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class product_has_attributeEntities : DbContext
    {
        public product_has_attributeEntities()
            : base("name=product_has_attributeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<attribute> attributes { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<product_attribute> product_attribute { get; set; }
        public virtual DbSet<variant> variants { get; set; }
        public virtual DbSet<variant_attribute> variant_attribute { get; set; }
    
        public virtual ObjectResult<getProductWithAttribute_Result1> getProductWithAttribute()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getProductWithAttribute_Result1>("getProductWithAttribute");
        }
    }
}
