//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class variant_option
    {
        public int id { get; set; }
        public Nullable<int> idVariant { get; set; }
        public Nullable<int> idOptionValue { get; set; }
    
        public virtual option_value option_value { get; set; }
        public virtual variant variant { get; set; }
    }
}
