//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class variant
    {
        public int id { get; set; }
        public string sku { get; set; }
        public Nullable<int> idProduct { get; set; }
        public string imagePath { get; set; }
    
        public virtual order_detail order_detail { get; set; }
    }
}
